# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Enterprise Subscription – MPN(e115c70e-6074-4a16-8a71-9f6aae0015ab)'
    subscriptionId: 'e115c70e-6074-4a16-8a71-9f6aae0015ab'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Test-rg'
    location: 'UK South'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/101-virtual-machine/azuredeploy.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/101-virtual-machine/azuredeploy.parameters.json'
    deploymentMode: 'Validation'

- task: CopyFiles@2
  inputs:
    SourceFolder: '101-virtual-machine'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'